import { db, sqlClient } from '../src/db/client'
import { siteRegistry } from '../src/db/schema'

const rows = [
  {
    key:'writing.runtime-truth-presentation-memory',
    kind:'section',
    parentKey:'writing',
    enabled:true,
    status:'published',
    sort:10,
    labelEn:'ARCHITECTURE',
    labelVi:'KIẾN TRÚC',
    titleEn:'Runtime truth and presentation memory should never be the same thing',
    titleVi:'Runtime truth và presentation memory không nên là cùng một thứ',
    summaryEn:'Discovery should answer what exists now. Presentation should transform that truth deterministically without writing visual preferences back into runtime identity. Mixing those layers makes infrastructure maps stale and dangerous.',
    summaryVi:'Discovery phải trả lời hiện tại đang tồn tại gì. Lớp trình bày chỉ nên biến đổi runtime truth theo quy tắc xác định, không ghi sở thích hiển thị ngược vào định danh runtime. Trộn hai lớp này khiến bản đồ hạ tầng nhanh lỗi thời và nguy hiểm.',
    meta:{ badge:{ en:'FIELD NOTE', vi:'GHI CHÉP' } },
  },
  {
    key:'writing.local-first-trust',
    kind:'section',
    parentKey:'writing',
    enabled:true,
    status:'published',
    sort:20,
    labelEn:'DATA / TRUST',
    labelVi:'DỮ LIỆU / TRUST',
    titleEn:'Local-first analytics needs explicit trust, not just faster charts',
    titleVi:'Phân tích local-first cần trust rõ ràng, không chỉ chart nhanh hơn',
    summaryEn:'A useful BI system separates cleaning, evidence, governed metrics and presentation so the user can see why a number deserves trust.',
    summaryVi:'Một hệ BI hữu ích phải tách làm sạch, bằng chứng, metric có quản trị và trình bày để người dùng thấy vì sao một con số đáng tin.',
    meta:{ badge:{ en:'LIGHTBI', vi:'LIGHTBI' } },
  },
  {
    key:'writing.ai-remote-boundaries',
    kind:'section',
    parentKey:'writing',
    enabled:true,
    status:'published',
    sort:30,
    labelEn:'REMOTE / CONTROL',
    labelVi:'REMOTE / CONTROL',
    titleEn:'AI remote control needs local boundaries',
    titleVi:'Điều khiển từ xa bằng AI cần ranh giới tại máy đích',
    summaryEn:'The useful boundary is not “AI can or cannot run commands.” It is identity, device-local policy, approval, scoped capabilities and an audit trail around every external modification.',
    summaryVi:'Ranh giới hữu ích không phải “AI có được chạy lệnh hay không”. Nó nằm ở identity, policy tại thiết bị, approval, capability có scope và audit quanh mọi thay đổi bên ngoài.',
    meta:{ badge:{ en:'LIGHT REMOTE', vi:'LIGHT REMOTE' } },
  },
  {
    key:'about.systems-builder',
    kind:'section',
    parentKey:'about',
    enabled:true,
    status:'published',
    sort:10,
    labelEn:'SYSTEMS BUILDER',
    labelVi:'SYSTEMS BUILDER',
    titleEn:'I build operational systems, not isolated screens',
    titleVi:'Tôi xây hệ thống vận hành, không chỉ các màn hình rời rạc',
    summaryEn:'My work sits across analytics, automation, infrastructure, remote operations and AI-assisted engineering, with a preference for systems that remain understandable when they become complex.',
    summaryVi:'Công việc của tôi trải qua phân tích dữ liệu, tự động hóa, hạ tầng, vận hành từ xa và kỹ thuật có AI hỗ trợ, với ưu tiên cho những hệ vẫn dễ hiểu khi trở nên phức tạp.',
    meta:{ badge:{ en:'THÁI DUY', vi:'THÁI DUY' } },
  },
  {
    key:'about.current-systems',
    kind:'section',
    parentKey:'about',
    enabled:true,
    status:'published',
    sort:20,
    labelEn:'CURRENT SYSTEMS',
    labelVi:'HỆ ĐANG XÂY',
    titleEn:'LightBI, Light Remote and Sentinel are different organs of the same practice',
    titleVi:'LightBI, Light Remote và Sentinel là các cơ quan khác nhau của cùng một cách làm',
    summaryEn:'One focuses on trusted data understanding, one on permission-aware remote execution, and one on sensing. The common thread is explicit state, strong boundaries and useful operator control.',
    summaryVi:'Một hệ tập trung vào hiểu dữ liệu đáng tin, một hệ vào thực thi từ xa có nhận thức quyền, và một hệ vào cảm nhận. Điểm chung là trạng thái rõ ràng, ranh giới mạnh và quyền điều khiển hữu ích cho operator.',
    meta:{ badge:{ en:'2026', vi:'2026' } },
  },
  {
    key:'about.principles',
    kind:'section',
    parentKey:'about',
    enabled:true,
    status:'published',
    sort:30,
    labelEn:'WORKING PRINCIPLES',
    labelVi:'NGUYÊN TẮC LÀM VIỆC',
    titleEn:'Truthful state, local control, durable evidence',
    titleVi:'Trạng thái trung thực, quyền kiểm soát cục bộ, bằng chứng bền vững',
    summaryEn:'I prefer quiet interfaces over fake activity, local enforcement over implied trust, and evidence that can survive beyond a single UI session.',
    summaryVi:'Tôi ưu tiên giao diện yên khi không có hoạt động thay vì chuyển động giả, enforcement cục bộ thay vì trust ngầm, và bằng chứng có thể tồn tại lâu hơn một phiên UI.',
    meta:{ badge:{ en:'METHOD', vi:'PHƯƠNG PHÁP' } },
  },
]

for (const row of rows) {
  await db.insert(siteRegistry)
    .values(row)
    .onConflictDoUpdate({
      target:siteRegistry.key,
      set:{
        kind:row.kind,
        parentKey:row.parentKey,
        enabled:row.enabled,
        status:row.status,
        sort:row.sort,
        labelEn:row.labelEn,
        labelVi:row.labelVi,
        titleEn:row.titleEn,
        titleVi:row.titleVi,
        summaryEn:row.summaryEn,
        summaryVi:row.summaryVi,
        meta:row.meta,
      },
    })
}

console.log(`public_section_rows=${rows.length}`)
await sqlClient.end()
