import { db, sqlClient } from '../src/db/client'
import { siteRegistry } from '../src/db/schema'

const rows = [
  {
    key:'writing.runtime-truth-presentation-memory',
    kind:'section',
    parentKey:'writing',
    enabled:true,
    status:'published',
    sort:10,
    labelEn:'ARCHITECTURE',
    labelVi:'KIẾN TRÚC',
    titleEn:'Runtime truth and presentation memory should never be the same thing',
    titleVi:'Runtime truth và presentation memory không nên bị trộn làm một',
    summaryEn:'Discovery should answer what exists now. Presentation should transform that truth deterministically without writing visual preferences back into runtime identity. Mixing those layers makes infrastructure maps stale and dangerous.',
    summaryVi:'Discovery chỉ nên trả lời hiện tại đang có gì. Lớp trình bày biến trạng thái đó thành giao diện theo quy tắc xác định, không ghi sở thích hiển thị ngược vào định danh runtime. Trộn hai lớp khiến bản đồ hạ tầng nhanh lỗi thời và khó tin cậy.',
    meta:{ badge:{ en:'FIELD NOTE', vi:'GHI CHÉP' } },
  },
  {
    key:'writing.local-first-trust',
    kind:'section',
    parentKey:'writing',
    enabled:true,
    status:'published',
    sort:20,
    labelEn:'DATA / TRUST',
    labelVi:'DỮ LIỆU / TRUST',
    titleEn:'Local-first analytics needs explicit trust, not just faster charts',
    titleVi:'Phân tích local-first cần trust rõ ràng, không chỉ cần biểu đồ nhanh hơn',
    summaryEn:'A useful BI system separates cleaning, evidence, governed metrics and presentation so the user can see why a number deserves trust.',
    summaryVi:'Một hệ BI hữu ích cần tách việc làm sạch dữ liệu, bằng chứng, metric có quản trị và phần trình bày, để người dùng hiểu vì sao một con số đáng tin.',
    meta:{ badge:{ en:'LIGHTBI', vi:'LIGHTBI' } },
  },
  {
    key:'writing.ai-remote-boundaries',
    kind:'section',
    parentKey:'writing',
    enabled:true,
    status:'published',
    sort:30,
    labelEn:'REMOTE / CONTROL',
    labelVi:'REMOTE / CONTROL',
    titleEn:'AI remote control needs local boundaries',
    titleVi:'Điều khiển từ xa bằng AI cần ranh giới ngay tại thiết bị',
    summaryEn:'The useful boundary is not “AI can or cannot run commands.” It is identity, device-local policy, approval, scoped capabilities and an audit trail around every external modification.',
    summaryVi:'Ranh giới quan trọng không chỉ là “AI có được chạy lệnh hay không”. Nó nằm ở identity, policy trên thiết bị, approval, capability được giới hạn phạm vi và audit trail cho mọi thay đổi bên ngoài.',
    meta:{ badge:{ en:'LIGHT REMOTE', vi:'LIGHT REMOTE' } },
  },
  {
    key:'about.systems-builder',
    kind:'section',
    parentKey:'about',
    enabled:true,
    status:'published',
    sort:10,
    labelEn:'THE PRACTICE',
    labelVi:'CÁCH LÀM',
    titleEn:'I work where software meets operations',
    titleVi:'Tôi làm việc ở giao điểm giữa phần mềm và vận hành',
    summaryEn:'I build across analytics, automation, infrastructure, remote operations and AI-assisted engineering. The interesting part is rarely one screen or one service; it is how the pieces keep making sense when the system grows, fails, changes and has to be operated by a real person.',
    summaryVi:'Tôi làm việc với phân tích dữ liệu, tự động hóa, hạ tầng, vận hành từ xa và kỹ thuật có AI hỗ trợ. Điều đáng quan tâm hiếm khi chỉ là một màn hình hay một service, mà là cách mọi mảnh ghép vẫn dễ hiểu khi hệ thống lớn lên, gặp lỗi, thay đổi và phải được con người vận hành.',
    meta:{ badge:{ en:'THÁI DUY', vi:'THÁI DUY' } },
  },
  {
    key:'about.current-systems',
    kind:'section',
    parentKey:'about',
    enabled:true,
    status:'published',
    sort:20,
    labelEn:'CURRENT SYSTEMS',
    labelVi:'HỆ HIỆN TẠI',
    titleEn:'Different products, one operating philosophy',
    titleVi:'Nhiều sản phẩm, cùng một triết lý vận hành',
    summaryEn:'LightBI turns messy operational data into governed understanding. Light Remote gives AI a permission-aware path to real machines. Sentinel learns to sense network, service and audio signals. They look different, but all three are built around explicit state, bounded authority and evidence the operator can inspect.',
    summaryVi:'LightBI biến dữ liệu vận hành lộn xộn thành hiểu biết có quản trị. Light Remote tạo đường truy cập tới máy thật với quyền hạn được kiểm soát. Sentinel học cách cảm nhận tín hiệu mạng, service và âm thanh. Dù khác nhau về hình thức, cả ba đều dựa trên trạng thái rõ ràng, quyền hạn có ranh giới và bằng chứng mà operator có thể kiểm tra.',
    meta:{ badge:{ en:'NOW', vi:'HIỆN TẠI' } },
  },
  {
    key:'about.principles',
    kind:'section',
    parentKey:'about',
    enabled:true,
    status:'published',
    sort:30,
    labelEn:'WORKING PRINCIPLES',
    labelVi:'NGUYÊN TẮC LÀM VIỆC',
    titleEn:'Local control, explicit trust, observable state',
    titleVi:'Kiểm soát cục bộ, trust rõ ràng, trạng thái quan sát được',
    summaryEn:'I prefer systems that fail closed, expose what they know and keep enforcement close to the machine or data they protect. Interfaces should be quiet when nothing is happening. Claims should have evidence. Automation should make authority clearer, not blur it.',
    summaryVi:'Tôi ưu tiên những hệ thống fail-closed, nói rõ chúng biết gì và giữ cơ chế thực thi chính sách gần máy hoặc dữ liệu cần bảo vệ. Giao diện nên yên khi không có gì xảy ra. Mọi kết luận nên có bằng chứng. Tự động hóa phải làm quyền hạn rõ ràng hơn, không khiến nó mơ hồ hơn.',
    meta:{ badge:{ en:'METHOD', vi:'PHƯƠNG PHÁP' } },
  },
  {
    key:'about.public-surface',
    kind:'section',
    parentKey:'about',
    enabled:true,
    status:'published',
    sort:40,
    labelEn:'WHY PUBLIC',
    labelVi:'VÌ SAO CÔNG KHAI',
    titleEn:'This site is a window, not a control plane',
    titleVi:'Website này là một ô cửa quan sát, không phải control plane',
    summaryEn:'I want the work to be inspectable: what is being built, what is running, what changed and what the systems taught me. The public surface shows real signals where they are safe to expose, while credentials, private topology and authority remain behind the boundary.',
    summaryVi:'Tôi muốn công việc có thể được quan sát: đang xây gì, thứ gì đang chạy, điều gì vừa thay đổi và hệ thống đã dạy tôi điều gì. Website chỉ hiển thị tín hiệu thực ở mức an toàn để công khai; credential, topology nội bộ và quyền điều khiển vẫn nằm phía sau ranh giới.',
    meta:{ badge:{ en:'THAIDUY.DIGITAL', vi:'THAIDUY.DIGITAL' } },
  },
]

for (const row of rows) {
  await db.insert(siteRegistry)
    .values(row)
    .onConflictDoUpdate({
      target:siteRegistry.key,
      set:{
        kind:row.kind,
        parentKey:row.parentKey,
        enabled:row.enabled,
        status:row.status,
        sort:row.sort,
        labelEn:row.labelEn,
        labelVi:row.labelVi,
        titleEn:row.titleEn,
        titleVi:row.titleVi,
        summaryEn:row.summaryEn,
        summaryVi:row.summaryVi,
        meta:row.meta,
      },
    })
}

console.log(`public_section_rows=${rows.length}`)
await sqlClient.end()
